/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.test;

import javax.annotation.Generated;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-11-01T11:08:00.228182328-03:00[America/Sao_Paulo]")
@Validated
public interface MyApi {

	@RequestMapping(
			method = RequestMethod.GET,
			value = "/endpoint",
			produces = { "application/json" }
	)
	ResponseEntity<String> myEndpoint(
			@Valid @RequestParam(value = "limit", required = false, defaultValue = "50") Integer limit
	);

}
